site_name: Day by day
repo_name: oaixnah/d
repo_url: https://github.com/oaixnah/d
theme:
  name: material
  language: zh
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
extra:
  analytics:
    provider: google
    property: G-KL781GK2EB
nav:
  - Home: index.md
  - 学习笔记:
      - MySQL 8.0:
          - 基础篇: study_notes/mysql8/basic.md
  - 读书笔记:
      - 纳瓦尔宝典: reading-notes/the-almanack-of-naval-ravikant.md